### ISSUE TITLE
Getting the time isnt right

### ISSUE THREAD

**Issue by iHaagcom** [jrentenaar/Office-365-Extractor#11]
------------------------------------------------------------------------------------------
|Extracting all available audit logs between  12/18/2021 05:13:43 and 03/18/2022 05:13:44 |
|Time interval:

Audit log search argument startDate (12/18/2021 5:13:43 AM) is later than endDate (12/18/2021 5:13:42 AM).
    + CategoryInfo          : InvalidArgument: (:) [Search-UnifiedAuditLog], ArgumentException
    + FullyQualifiedErrorId : [Server=ME3PR01MB6739,RequestId=d75e236c-3298-42bb-d00b-9403efd424da,TimeStamp=3/18/2022
   5:14:39 AM] [FailureCategory=Cmdlet-ArgumentException] DAE4C2A7,Microsoft.Exchange.Management.SystemConfigurationTa
  sks.SearchUnifiedAuditLog
    + PSComputerName        : outlook.office365.com

**Comment by JoeyRentenaar** [comment]
Hi, are you still having this issue? In what format are you inputting the date? Since there are some differences in for example US vs Europe. The script will convert the date to: yyyy-MM-dd HH:mm:ss

**Comment by iHaagcom** [comment]
Hi Joey, Just hitting enter. Seems to be getting the date just fine tho. I think there is some other issue, its not the date. I'm getting other issues now:
Starting a command on the remote server failed with the following error message : The I/O operation has been aborted because of either a thread exit or an application request. For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (outlook.office365.com:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : outlook.office365.com
    
    Audit log search argument startDate (12/27/2021 11:09:13 PM) is later than endDate (12/27/2021 11:09:12 PM).
    + CategoryInfo          : InvalidArgument: (:) [Search-UnifiedAuditLog], ArgumentException
    + FullyQualifiedErrorId : [Server=ME3PR01MB6739,RequestId=e0vsdfsfsgsgdsdg-0s-dgs-dg-sdg,TimeStamp=3/27/2022 11:17:58 PM] [FailureCategory=Cmdlet-ArgumentException] D8F4DE00,Microsoft.Exchange.Mana
   gement.SystemConfigurationTasks.SearchUnifiedAuditLog
    + PSComputerName        : outlook.office365.com
    
Processing data from remote server outlook.office365.com failed with the following error message: WS-Management cannot process the request. The operation failed because of an HTTP error. The HTTP error
(12152) is: The server returned an invalid or unrecognized response . For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (outlook.office365.com:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : outlook.office365.com

Starting a command on the remote server failed with the following error message : The I/O operation has been aborted because of either a thread exit or an application request. For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (outlook.office365.com:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : outlook.office365.com
