### ISSUE TITLE
After 1 hour of execution, error : "Access is denied"

### ISSUE THREAD

**Issue by Mcelsans** [jrentenaar/Office-365-Extractor#2]
When I run the script, records are correctly being downloaded.
But each time,  after approximatively 1 hour, the script stop with the following error :

INFO: Retrieving audit logs between 04/15/2019 23:03:45 and 04/15/2019 23:03:45
Starting a command on the remote server failed with the following error message : Access is denied. For more
information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OperationStopped: (outlook.office365.com:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : outlook.office365.com

I have to relaunch the script every hour in order to get all the logs.

**Comment by PwC-IR** [comment]
Hey, sorry for the late response. 
Could you try to run the script from a different network to make sure nothing gets blocked? We have never seen this error before but it looks like a Transport error. 

Does your computer go on standby mode after one hour?

**Comment by jrentenaar** [comment]
Hey, sorry for the late response.
Could you try to run the script from a different network to make sure nothing gets blocked? We have never seen this error before but it looks like a Transport error.

Does your computer go on standby mode after one hour?

**Comment by Mcelsans** [comment]
Hi, thank you for your response. 
I have done some test and the issue only occurs when MFA is activated.

I have modified the script to support MFA :

#$UserCredential = Get-Credential
#$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
#Import-PSSession $Session

Change to :
Connect-EXOPSSession -UserPrincipalName $UserCredential
$Session = Get-PSSession | where {$_.ComputerName -eq "outlook.office365.com"}


Without MFA, there is no issue, the script goes on.
But with MFA, I 'll still get the same error after 1 hour of execution (I have desactivated the standby mode on my computer)
If you have any idea how to pull the logs with MFA  , I am interrested.

Thanks

**Comment by jrentenaar** [comment]
Thanks for your reply, this is a new error message to us and we will do some research into it.

What we do at most of our clients is request a new user account with only the "View-Only Audit Logs" privileges/role and MFA disabled for that account. With this account you can then extract the Unified Audit Log.

**Comment by jrentenaar** [comment]
In the Microsoft documentation I found the following:
_When you use the Exchange Online Remote PowerShell Module, your session will end after one hour, which can be problematic for long-running scripts or processes._ 

We are not aware of a way around this issue yet. I would suggest the work around mentioned above:
_What we do at most of our clients is request a new user account with only the "View-Only Audit Logs" privileges/role and MFA disabled for that account. With this account you can then extract the Unified Audit Log._
