### ISSUE TITLE
power shell new version 5.1.19041.1 get the issue but older version run successful ,plz help below error also posted 

### ISSUE THREAD

**Issue by Suresh598** [jrentenaar/Office-365-Extractor#5]
--------------------------------------------------------------------------
|Extracting audit logs between  04/01/2020 00:00:00 and 06/27/2020 00:00:00|
|Time interval: 60                                                                       |
----------------------------------------------------------------------------
The following RecordTypes are configured to be extracted:
-ExchangeItem

Foreach ($record in $RecordTypes.Split(",")){
			$SpecificResult = Search-UnifiedAuditLog -StartDate $StartDate -EndDate $EndDate -RecordType $record -UserIds $Userstoextract -ResultSize 1 | out-string -Stream | select-string ResultCount

Search-UnifiedAuditLog : The term **'Search-UnifiedAuditLog'** is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At D:\NEW TEST\Office-365-Extractor-master\Office-365-Extractor-master\Office365_Extractor.ps1:563 char:22
+             $SpecificResult = Search-UnifiedAuditLog -StartDate $Star ...
+                               ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Search-UnifiedAuditLog:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
No logs available for ExchangeItem

Remove-PSSession : Cannot validate argument on parameter 'Id'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\NEW TEST\Office-365-Extractor-master\Office-365-Extractor-master\Office365_Extractor.ps1:690 char:25
+             Remove-PSSession -ID $Session.ID
+                                  ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-PSSession], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.RemovePSSessionCommand

Regardss
Suresh

**Comment by jrentenaar** [comment]
Hi Suresh,

Sorry for the late response. Did you manage to solve this issue or are you still running into problems?

Could you try to run the following three commands one by one in PowerShell:
`$UserCredential = Get-Credential
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session`

If this results in an error, could you then try to go to the GUI interface with the same account and see if you are able to view the Unified Audit Logging in the admin center? The module should be installed by default if you run the script on one of the following Windows versions:
Windows 10, Windows 8.1, Windows 8, or Windows 7 Service Pack 1 (SP1)
Windows Server 2019, Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, or Windows Server 2008 R2 SP1

**Comment by Suresh598** [comment]
Hi Team,

in the above cmdlets line is working fine, but  the one doubt  office -365
-Extractor  i select  in this
option   AzureActiveDirectoryStsLogon_AuditRecords   after the collect that
logs only login field or successfully reports showing.
I need with end user logon time slot and exactly  location (not in country
) with area location name.

**Comment by jrentenaar** [comment]
Hi Suresh,

What information are you looking for? I see that you extracted the RecordType "AzureActiveDirectoryStsLogon", this log contains the following information: Secure Token Service (STS) logon events in Azure Active Directory.

If you are trying to find the time of login and a location I would recommend to extract the RecordType "AzureActiveDirectory". This RecordType contains information around login times and IP-address which you then can use to do a lookup. 

I am not aware of a method to find the exact location of a user.

**Comment by Suresh598** [comment]
Hi Team,
Actually i would like to inform that AzureActiveDirectory this RecordType
contains information around login times and IP-address Devices type details.
